package com.lsi.businesscard;

import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.provider.ContactsContract;
import android.view.*;
import android.widget.*;
import java.io.File;

public class DetailActivity extends Activity {
    private interface PhotoDisplay{void accept(int index);}
    private DbHelper db;private long id;private Contact c;private LinearLayout root;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DbHelper(this);id=getIntent().getLongExtra("id",-1);show();}
    @Override protected void onResume(){super.onResume();if(db!=null)show();}
    private void show(){
        c=db.get(id);if(c==null){finish();return;}
        LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(Color.WHITE);
        LinearLayout bar=new LinearLayout(this);bar.setPadding(Ui.dp(this,12),Ui.dp(this,4),Ui.dp(this,12),Ui.dp(this,4));bar.setGravity(Gravity.CENTER_VERTICAL);
        Button back=Ui.button(this,"‹ 목록"),fav=Ui.button(this,c.favorite==1?"★":"☆"),edit=Ui.button(this,"수정"),more=Ui.button(this,"⋮");fav.setContentDescription("즐겨찾기 설정 또는 해제");more.setContentDescription("더 보기");bar.addView(back);bar.addView(new Space(this),Ui.weight(1));for(Button button:new Button[]{fav,edit,more}){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(Ui.dp(this,4),0,0,0);bar.addView(button,lp);}page.addView(bar);page.addView(Ui.divider(this));
        back.setOnClickListener(v->finish());edit.setOnClickListener(v->editCard());fav.setOnClickListener(v->{c.favorite=c.favorite==1?0:1;db.setFavorite(id,c.favorite==1);fav.setText(c.favorite==1?"★":"☆");});more.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("명함 관리").setItems(new String[]{"정보 공유", "명함 삭제"},(d,w)->{if(w==0)shareMenu();else deleteCard();}).show());
        ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,16),Ui.dp(this,8),Ui.dp(this,16),Ui.dp(this,20));sv.addView(root);page.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        root.addView(Ui.text(this,nz(c.get("name"),"(이름 없음)"),24,true));addLine(join(" · ",c.get("company1"),c.get("department1"),c.get("title1")),16);if(!c.get("group_name").isEmpty())root.addView(Ui.badge(this,c.get("group_name")));
        addPhotos();section("연락처");
        for(String k:new String[]{"mobile1","mobile2","mobile3"})contactRow("휴대폰",c.get(k),0);
        for(String k:new String[]{"phone1","phone2","phone3"})contactRow("전화",c.get(k),1);
        for(String k:new String[]{"fax1","fax2","fax3"})contactRow("팩스",c.get(k),2);
        for(String k:new String[]{"email1","email2","email3"})contactRow("이메일",c.get(k),3);
        for(String k:new String[]{"address1","address2","address3"})contactRow("주소",c.get(k),4);
        contactRow("웹사이트",c.get("website"),5);
        String notes=join("\n",c.get("note1"),c.get("note2"),c.get("note3"));if(!notes.isEmpty()){section("메모");TextView preview=Ui.text(this,notes,15,false);preview.setTextIsSelectable(true);preview.setMaxLines(3);preview.setEllipsize(android.text.TextUtils.TruncateAt.END);root.addView(preview);Button expand=Ui.button(this,"메모 전체 보기");root.addView(expand);expand.setOnClickListener(v->{preview.setMaxLines(Integer.MAX_VALUE);preview.setEllipsize(null);expand.setVisibility(View.GONE);});}
        section("만남 기록");field("만난 날짜",c.get("met_at"));field("만난 장소",c.get("met_place"));field("만남 / 연락 기록",c.get("meeting_notes"));
        LinearLayout meeting=new LinearLayout(this);Button record=Ui.button(this,"＋ 만남 기록 추가"),calendar=Ui.button(this,"연락 약속 · 달력");meeting.addView(record,Ui.weight(1));meeting.addView(calendar,Ui.weight(1));root.addView(meeting);record.setOnClickListener(v->startActivity(new Intent(this,EditActivity.class).putExtra("id",id).putExtra("focus_meeting",true)));calendar.setOnClickListener(v->calendar());
        Button extra=Ui.button(this,"추가 정보 ▾");root.addView(extra);LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);LinearLayout body=root;root=info;
        field("회사 2",join(" / ",c.get("company2"),c.get("department2"),c.get("title2")));field("회사 3",join(" / ",c.get("company3"),c.get("department3"),c.get("title3")));field("업종",c.get("industry"));field("위치",c.get("location_text"));field("메신저",c.get("instant_message"));field("SNS",c.get("sns_account"));field("별명",c.get("nickname"));field("생일",c.get("birthday"));field("기념일",c.get("anniversary"));field("가져온 곳",c.get("source"));field("생성일",c.get("created_at"));field("수정일",c.get("updated_at"));root=body;info.setVisibility(View.GONE);root.addView(info);extra.setOnClickListener(v->{boolean open=info.getVisibility()!=View.VISIBLE;info.setVisibility(open?View.VISIBLE:View.GONE);extra.setText(open?"추가 정보 ▴":"추가 정보 ▾");});
        LinearLayout actions=new LinearLayout(this);Button contacts=Ui.primary(this,"연락처에 저장"),share=Ui.button(this,"공유");actions.addView(contacts,Ui.weight(1));actions.addView(share,Ui.weight(1));root.addView(Ui.gap(this,8));root.addView(actions);contacts.setOnClickListener(v->saveToContacts());share.setOnClickListener(v->shareMenu());Ui.setContentView(this,page);
    }
    private void editCard(){startActivity(new Intent(this,EditActivity.class).putExtra("id",id));}
    private void deleteCard(){new AlertDialog.Builder(this).setTitle("명함 삭제").setMessage("이 명함과 사용하지 않는 해당 사진을 삭제할까요?").setNegativeButton("취소",null).setPositiveButton("삭제",(d,w)->{db.deleteWithUnusedImages(id);finish();}).show();}
    private void calendar(){Intent i=new Intent(Intent.ACTION_INSERT,android.provider.CalendarContract.Events.CONTENT_URI);i.putExtra(android.provider.CalendarContract.Events.TITLE,c.get("name")+" 연락 / 만남");i.putExtra(android.provider.CalendarContract.Events.EVENT_LOCATION,c.get("met_place"));i.putExtra(android.provider.CalendarContract.Events.DESCRIPTION,c.get("company1")+"\n"+nz(c.get("mobile1"),c.get("phone1"))+"\n"+c.get("meeting_notes"));safeStart(i,"달력 앱을 열 수 없습니다.");}
    private void contactRow(String label,String value,int kind){
        if(value==null||value.trim().isEmpty())return;String raw=value.trim();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,Ui.dp(this,5),0,Ui.dp(this,5));
        LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);TextView tag=Ui.text(this,label,12,false);Ui.compactText(tag,1);tag.setTextColor(Color.rgb(104,113,125));text.addView(tag);TextView val=Ui.text(this,kind<=2?PhoneDisplay.format(raw):raw,16,false);val.setPadding(0,0,0,0);text.addView(val);row.addView(text,Ui.weight(1));
        if(kind!=2){Button open=Ui.button(this,kind<=1?"전화":kind==3?"메일":kind==4?"지도":"열기");open.setTextSize(12*Ui.textScale(this));open.setPadding(Ui.dp(this,5),0,Ui.dp(this,5),0);row.addView(open);View.OnClickListener click=v->{if(kind<=1)dial(raw);else if(kind==3)email(raw);else if(kind==4)map(raw);else web(raw);};open.setOnClickListener(click);text.setOnClickListener(click);}
        if(kind==0){Button sms=Ui.button(this,"문자");sms.setTextSize(12*Ui.textScale(this));sms.setPadding(Ui.dp(this,5),0,Ui.dp(this,5),0);row.addView(sms);sms.setOnClickListener(v->safeStart(new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:"+Uri.encode(raw))),"문자 앱을 열 수 없습니다."));}
        Button copy=Ui.button(this,"복사");copy.setTextSize(12*Ui.textScale(this));copy.setPadding(Ui.dp(this,5),0,Ui.dp(this,5),0);copy.setContentDescription(label+" 복사");row.addView(copy);copy.setOnClickListener(v->copy(raw));text.setOnLongClickListener(v->{copy(raw);return true;});root.addView(row);root.addView(Ui.divider(this));
    }
    private void addPhotos(){java.util.List<String> paths=new java.util.ArrayList<>(),labels=new java.util.ArrayList<>();String[] keys={"image_front","image_back","image_front2","image_back2"},titles={"앞면","뒷면","앞면 2","뒷면 2"};for(int i=0;i<keys.length;i++){String path=c.get(keys[i]);if(!path.isEmpty()&&new File(path).isFile()){paths.add(path);labels.add(titles[i]);}}if(paths.isEmpty())return;
        TextView hint=Ui.label(this,"명함 사진 · 누르면 확대");root.addView(hint);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackground(Ui.rounded(Color.rgb(247,249,252),10,this));final int[] current={0};java.util.List<Button> photoTabs=new java.util.ArrayList<>();PhotoDisplay display=index->{current[0]=index;for(int i=0;i<photoTabs.size();i++)Ui.styleButton(photoTabs.get(i),i==index);image.setImageBitmap(ImageUtil.thumbnail(paths.get(index),1600));image.setContentDescription("명함 "+labels.get(index)+" 사진 확대");};
        if(paths.size()>1){LinearLayout tabs=new LinearLayout(this);for(int i=0;i<paths.size();i++){final int index=i;Button tab=Ui.button(this,labels.get(i));photoTabs.add(tab);tabs.addView(tab,Ui.weight(1));tab.setOnClickListener(v->display.accept(index));}root.addView(tabs);}root.addView(image,new LinearLayout.LayoutParams(-1,Ui.dp(this,190)));display.accept(0);image.setOnClickListener(v->showImage(paths.get(current[0]),"명함 "+labels.get(current[0])));
    }
    private void shareMenu(){java.util.List<String> names=new java.util.ArrayList<>();names.add("명함 정보 (텍스트)");names.add("연락처 파일 (VCF)");java.util.List<String> photos=new java.util.ArrayList<>();for(String key:new String[]{"image_front","image_back","image_front2","image_back2"}){String path=c.get(key);if(!path.isEmpty()&&new File(path).isFile())photos.add(path);}if(!photos.isEmpty())names.add("명함 사진");new AlertDialog.Builder(this).setTitle("공유").setItems(names.toArray(new String[0]),(d,w)->{if(w==0)shareText();else if(w==1)shareVcard();else if(photos.size()==1)sharePhoto(photos.get(0));else{String[] labels=new String[photos.size()];for(int j=0;j<labels.length;j++)labels[j]="명함 사진 "+(j+1);new AlertDialog.Builder(this).setTitle("공유할 사진").setItems(labels,(x,y)->sharePhoto(photos.get(y))).show();}}).show();}
    private void sharePhoto(String path){try{Bitmap bitmap=ImageUtil.oriented(path,4000);if(bitmap==null)throw new java.io.IOException("사진을 읽을 수 없습니다.");File dir=new File(getCacheDir(),"camera");if(!dir.exists())dir.mkdirs();File file=new File(dir,"shared_card_"+id+".jpg");try(java.io.OutputStream out=new java.io.FileOutputStream(file)){if(!bitmap.compress(Bitmap.CompressFormat.JPEG,95,out))throw new java.io.IOException("사진 파일 생성 실패");}Uri uri=CardFileProvider.uriFor(this,file);Intent i=new Intent(Intent.ACTION_SEND);i.setType("image/jpeg");i.putExtra(Intent.EXTRA_STREAM,uri);i.setClipData(ClipData.newRawUri("명함 사진",uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);safeStart(Intent.createChooser(i,"명함 사진 공유"),"공유할 앱을 열 수 없습니다.");}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void section(String s){root.addView(Ui.section(this,s));}
    private void field(String label,String val){if(val==null||val.trim().isEmpty())return;TextView t=Ui.text(this,label+"\n"+val.trim(),15,false);t.setTextIsSelectable(true);root.addView(t);}
    private void addLine(String s,int sp){if(s!=null&&!s.isEmpty())root.addView(Ui.text(this,s,sp,false));}
    private void showImage(String path,String title){Bitmap b=ImageUtil.thumbnail(path,2600);if(b==null)return;ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setImageBitmap(b);ScrollView sv=new ScrollView(this);sv.addView(im);new AlertDialog.Builder(this).setTitle(title).setView(sv).setPositiveButton("닫기",null).show();}
    private void dial(String s){safeStart(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(s))),"전화 앱을 열 수 없습니다.");}
    private void email(String s){safeStart(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"+Uri.encode(s))),"메일 앱을 열 수 없습니다.");}
    private void map(String s){safeStart(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(s))),"지도 앱을 열 수 없습니다.");}
    private void web(String s){String u=s.startsWith("http://")||s.startsWith("https://")?s:"https://"+s;safeStart(new Intent(Intent.ACTION_VIEW,Uri.parse(u)),"웹 주소를 열 수 없습니다.");}
    private void safeStart(Intent i,String msg){try{startActivity(i);}catch(Exception e){Toast.makeText(this,msg,Toast.LENGTH_SHORT).show();}}
    private void copy(String s){android.content.ClipboardManager m=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);m.setPrimaryClip(ClipData.newPlainText("명함 정보",s));Toast.makeText(this,"클립보드에 복사했습니다.",Toast.LENGTH_SHORT).show();}
    private void saveToContacts(){Intent i=new Intent(Intent.ACTION_INSERT,ContactsContract.Contacts.CONTENT_URI);i.putExtra(ContactsContract.Intents.Insert.NAME,c.get("name"));i.putExtra(ContactsContract.Intents.Insert.COMPANY,c.get("company1"));i.putExtra(ContactsContract.Intents.Insert.JOB_TITLE,c.get("title1"));i.putExtra(ContactsContract.Intents.Insert.PHONE,nz(c.get("mobile1"),c.get("phone1")));i.putExtra(ContactsContract.Intents.Insert.EMAIL,c.get("email1"));safeStart(i,"연락처 앱을 열 수 없습니다.");}
    private void shareVcard(){try{File dir=new File(getCacheDir(),"camera");if(!dir.exists())dir.mkdirs();File file=new File(dir,"contact_"+id+".vcf");DataExchange.writeVcard(file,java.util.Collections.singletonList(c));Uri uri=CardFileProvider.uriFor(this,file);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/vcard");i.putExtra(Intent.EXTRA_STREAM,uri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("연락처 파일",uri));safeStart(Intent.createChooser(i,"연락처 파일 공유"),"공유할 앱을 열 수 없습니다.");}catch(Exception e){Toast.makeText(this,"연락처 파일 생성 실패: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void shareText(){StringBuilder b=new StringBuilder();append(b,c.get("name"));append(b,join(" / ",c.get("company1"),c.get("department1"),c.get("title1")));for(String k:new String[]{"mobile1","mobile2","mobile3","phone1","phone2","phone3","email1","email2","email3","address1","website"})append(b,c.get(k));Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,b.toString());safeStart(Intent.createChooser(i,"명함 정보 공유"),"공유할 앱을 열 수 없습니다.");}
    private static void append(StringBuilder b,String s){if(s!=null&&!s.trim().isEmpty()){if(b.length()>0)b.append('\n');b.append(s.trim());}}
    private static String nz(String a,String b){return a==null||a.isEmpty()?b:a;}private static String join(String sep,String...s){StringBuilder b=new StringBuilder();for(String x:s)if(x!=null&&!x.trim().isEmpty()){if(b.length()>0)b.append(sep);b.append(x.trim());}return b.toString();}
}
