package com.lsi.businesscard;

import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import android.text.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final int REQ_XLSX_ZIP=101,REQ_ZIP=102,REQ_SAVE_BACKUP=103,REQ_RESTORE=104,REQ_XLSX_ONLY=105,REQ_EXPORT=106;
    private DbHelper db; private EditText search; private ListView list; private TextView count,empty; private Button favButton,groupButton,sortButton; private int sortMode=1;
    private ActionMode selectionMode;private final Set<Long> selected=new LinkedHashSet<>();private List<Contact> visibleItems=new ArrayList<>();private File pendingExport;
    private String lastQuery="",lastGroup="";private int lastSort=-1;private boolean lastFavorites;
    private File camXlsx,pendingBackup; private boolean favoritesOnly=false; private String groupFilter="";

    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DbHelper(this);if(!getPreferences(MODE_PRIVATE).getBoolean("recentDefault21",false))getPreferences(MODE_PRIVATE).edit().putInt("sortMode",1).putBoolean("recentDefault21",true).apply();sortMode=getPreferences(MODE_PRIVATE).getInt("sortMode",1);if(sortMode<0||sortMode>=DbHelper.SORT_LABELS.length)sortMode=1;if(b!=null){String path=b.getString("pendingExport","");if(!path.isEmpty())pendingExport=new File(path);path=b.getString("camXlsx","");if(!path.isEmpty())camXlsx=new File(path);path=b.getString("pendingBackup","");if(!path.isEmpty())pendingBackup=new File(path);}buildUi();if(b!=null){search.setText(b.getString("query",""));groupFilter=b.getString("group","");favoritesOnly=b.getBoolean("favoritesOnly");groupButton.setText("그룹: "+(groupFilter.isEmpty()?"전체":groupFilter));favButton.setText(favoritesOnly?"★ 즐겨찾기":"☆ 즐겨찾기");Ui.styleButton(favButton,favoritesOnly);Ui.styleButton(groupButton,!groupFilter.isEmpty());}refresh();}
    @Override protected void onResume(){super.onResume();if(db!=null)refresh();}

    private void buildUi(){
        getWindow().setStatusBarColor(Color.rgb(13,71,161));
        getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE|WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
        LinearLayout root=new LinearLayout(this);root.setFocusableInTouchMode(true);root.requestFocus();root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,246,248));root.setPadding(Ui.dp(this,12),Ui.dp(this,4),Ui.dp(this,12),Ui.dp(this,4));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=Ui.text(this,"명함관리 LSI",22,true);top.addView(title,Ui.weight(1));count=Ui.badge(this,"");top.addView(count);Button plus=Ui.button(this,"＋");plus.setContentDescription("명함 추가 메뉴");LinearLayout.LayoutParams plusLp=new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48));plusLp.setMargins(Ui.dp(this,6),0,0,0);top.addView(plus,plusLp);plus.setOnClickListener(v->showAddMenu());root.addView(top,Ui.mp(this));

        search=Ui.edit(this,"검색 · 이름 / 회사 / 전화 / 메모");search.setBackground(Ui.rounded(Color.WHITE,18,this));search.setPadding(Ui.dp(this,12),Ui.dp(this,4),Ui.dp(this,12),Ui.dp(this,4));search.setMinimumHeight(Ui.dp(this,48));root.addView(search,Ui.mp(this));
        LinearLayout filters=new LinearLayout(this);filters.setGravity(Gravity.CENTER_VERTICAL);favButton=Ui.button(this,"☆ 즐겨찾기");groupButton=Ui.button(this,"그룹: 전체");sortButton=Ui.button(this,sortLabel());for(Button b:new Button[]{favButton,groupButton,sortButton}){b.setTextSize(12*Ui.textScale(this));b.setPadding(Ui.dp(this,3),Ui.dp(this,1),Ui.dp(this,3),Ui.dp(this,1));b.setMinHeight(Ui.dp(this,40));b.setMinimumHeight(Ui.dp(this,40));b.setMaxLines(2);b.setEllipsize(TextUtils.TruncateAt.END);LinearLayout.LayoutParams lp=Ui.weight(1);lp.setMargins(Ui.dp(this,2),Ui.dp(this,2),Ui.dp(this,2),Ui.dp(this,3));filters.addView(b,lp);}root.addView(filters,Ui.mp(this));
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh();}public void afterTextChanged(Editable e){}});
        favButton.setOnClickListener(v->{favoritesOnly=!favoritesOnly;favButton.setText(favoritesOnly?"★ 즐겨찾기":"☆ 즐겨찾기");Ui.styleButton(favButton,favoritesOnly);refresh();});groupButton.setOnClickListener(v->chooseGroup());sortButton.setOnClickListener(v->chooseSort());
        list=new ListView(this);list.setDividerHeight(1);list.setBackgroundColor(Color.WHITE);empty=Ui.text(this,"저장된 명함이 없습니다.\n‘명함 스캔’ 또는 ‘＋ 새 명함’을 사용하세요.\n기존 명함은 ‘관리 → 가져오기’로 옮길 수 있습니다.",16,false);empty.setGravity(Gravity.CENTER);
        FrameLayout content=new FrameLayout(this);content.addView(list,new FrameLayout.LayoutParams(-1,-1));content.addView(empty,new FrameLayout.LayoutParams(-1,-1));list.setEmptyView(empty);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
        list.setOnItemClickListener((p,v,pos,id)->{Contact c=(Contact)p.getItemAtPosition(pos);if(selectionMode!=null){toggleSelected(c.id);return;}startActivity(new Intent(this,DetailActivity.class).putExtra("id",c.id));});

        list.setOnItemLongClickListener((p,v,pos,id)->{beginSelection();toggleSelected(((Contact)p.getItemAtPosition(pos)).id);return true;});
        LinearLayout bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER_VERTICAL);bottom.setPadding(0,Ui.dp(this,3),0,0);
        bottom.addView(navItem("추가","＋",()->showAddMenu()),new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));
        bottom.addView(navItem("관리","☰",()->showManageMenu()),new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));
        ScanButton camera=new ScanButton(this);camera.setContentDescription("명함 스캔");camera.setOnClickListener(v->startActivity(new Intent(this,EditActivity.class).putExtra("scan",true)));LinearLayout.LayoutParams cameraLp=new LinearLayout.LayoutParams(Ui.dp(this,56),Ui.dp(this,56));cameraLp.setMargins(Ui.dp(this,6),0,Ui.dp(this,6),0);bottom.addView(camera,cameraLp);
        bottom.addView(navItem("가져오기","▱",()->showImportMenu()),new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));
        bottom.addView(navItem("설정","⚙",()->showSettings()),new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));root.addView(bottom,Ui.mp(this));Ui.setContentView(this,root);
    }

    private View navItem(String label,String symbol,Runnable action){LinearLayout item=new LinearLayout(this);item.setOrientation(1);item.setGravity(Gravity.CENTER);NavIcon icon=new NavIcon(this,label);item.addView(icon,new LinearLayout.LayoutParams(Ui.dp(this,26),Ui.dp(this,26)));TextView title=Ui.text(this,label,10,false);title.setTextColor(Color.rgb(80,105,130));item.addView(title);item.setContentDescription(label);item.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(Color.rgb(211,229,245)),null,null));item.setClickable(true);item.setFocusable(true);item.setOnClickListener(v->action.run());return item;}
    private void showSettings(){new AlertDialog.Builder(this).setTitle("환경설정").setItems(new String[]{"스캔 방식: "+ScanSettings.label(this),"글자 크기","사용 안내"},(d,w)->{if(w==0)chooseScanMode();else if(w==1)chooseTextSize();else showGuide();}).setNegativeButton("닫기",null).show();}
    private void chooseScanMode(){new AlertDialog.Builder(this).setTitle("기본 스캔 방식").setSingleChoiceItems(new String[]{"자동 촬영 · 안정되면 촬영 후 모서리 보정","수동 촬영 · 촬영 후 모서리 보정"},ScanSettings.manual(this)?1:0,(d,w)->{ScanSettings.setManual(this,w==1);d.dismiss();toast("스캔 방식: "+ScanSettings.label(this));}).setNegativeButton("취소",null).show();}

    private String sortLabel(){String[] labels={"입력 오래된순","최근 저장순","이름 가나다순","이름 역순","회사 가나다순","회사 역순","최근 수정순","최근 만남순","만남 오래된순"};return labels[sortMode]+" ▾";}
    private void refresh(){if(db==null||list==null)return;String query=search==null?"":search.getText().toString();boolean same=query.equals(lastQuery)&&groupFilter.equals(lastGroup)&&sortMode==lastSort&&favoritesOnly==lastFavorites;int position=list.getFirstVisiblePosition();View first=list.getChildAt(0);int top=first==null?0:first.getTop();List<Contact> items=db.search(query,favoritesOnly,groupFilter,sortMode);visibleItems=items;list.setAdapter(new ContactAdapter(this,items,selected,this::showCardMenu));if(same)list.setSelectionFromTop(position,top);lastQuery=query;lastGroup=groupFilter;lastSort=sortMode;lastFavorites=favoritesOnly;int total=db.count();count.setText(items.size()==total?total+"명":"검색 "+items.size()+"명\n전체 "+total+"명");empty.setText(total==0?"저장된 명함이 없습니다.\n‘명함 스캔’ 또는 ‘＋ 새 명함’을 사용하세요.\n기존 명함은 ‘관리 → 가져오기’로 옮길 수 있습니다.":"검색 결과가 없습니다.\n검색어 또는 즐겨찾기·그룹 조건을 확인하세요.");if(selectionMode!=null)selectionMode.setTitle(selected.size()+"명 선택");}
    private void chooseSort(){new AlertDialog.Builder(this).setTitle("명함 정렬").setSingleChoiceItems(DbHelper.SORT_LABELS,sortMode,(d,w)->{setSort(w);d.dismiss();}).setNegativeButton("취소",null).show();}
    private void chooseGroup(){List<String> g=db.groups();ArrayList<String>x=new ArrayList<>();x.add("전체");x.addAll(g);new AlertDialog.Builder(this).setTitle("그룹 선택").setItems(x.toArray(new String[0]),(d,w)->{groupFilter=w==0?"":x.get(w);groupButton.setText("그룹: "+(groupFilter.isEmpty()?"전체":groupFilter));Ui.styleButton(groupButton,!groupFilter.isEmpty());refresh();}).show();}

    @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("camXlsx",camXlsx==null?"":camXlsx.getAbsolutePath());b.putString("pendingExport",pendingExport==null?"":pendingExport.getAbsolutePath());b.putString("pendingBackup",pendingBackup==null?"":pendingBackup.getAbsolutePath());b.putString("query",search.getText().toString());b.putString("group",groupFilter);b.putBoolean("favoritesOnly",favoritesOnly);}
    private void showGuide(){new AlertDialog.Builder(this).setTitle("명함관리 LSI 사용 안내").setMessage("• 기본 목록은 최근 저장한 명함부터 표시됩니다. 수정만 한 명함의 입력 순서는 유지됩니다.\n• 정렬 버튼에서 이름·회사·입력·수정·만난 날짜 순서를 선택할 수 있습니다.\n• 검색은 여러 단어, 초성(예: ㄱㅁㅅ), 전화번호 일부를 지원합니다.\n• 명함 스캔 → 외곽선 자동 인식·기울기 보정 → 글자 인식 → 내용 확인 → 저장. 환경설정 → 스캔 방식에서 자동 또는 수동 촬영을 선택할 수 있습니다. 두 방식 모두 외곽선을 찾고 촬영 후 네 모서리를 수정할 수 있습니다. Google 스캐너는 촬영 화면의 도움말에서 사용할 수 있습니다. 저장한 새 명함 사진은 갤러리의 명함관리 LSI 앨범에도 보관합니다. Google 스캐너는 처음 사용 시 구성 요소 다운로드가 필요할 수 있습니다. 한자는 한글 독음으로 변환하며 원문을 보관합니다. 여러 독음이 있는 이름은 저장 전에 확인하세요. 여러 장은 ‘저장 후 다음 명함 촬영’을 사용하세요.\n• 명함을 길게 눌러 여러 명함을 선택하고 그룹·즐겨찾기·삭제·내보내기를 처리합니다.\n• 만난 날짜·장소·기록은 수정 화면에서 입력합니다. 연락 약속은 상세 화면의 ‘연락 약속 · 달력’ 버튼으로 등록합니다.\n• Excel·CSV·VCF는 연락처 정보를 내보냅니다. 사진까지 옮길 때는 사진 포함 백업 ZIP을 사용하세요.\n• 내보내기에서 ‘공유’를 선택하면 이메일·Quick Share·블루투스 등으로 파일을 보낼 수 있습니다.\n• CSV는 Excel 안전 처리를 위해 수식 시작 문자에 작은따옴표를 붙입니다. 정확한 재가져오기는 Excel 파일을 사용하세요.\n• 백업은 복원할 때 기존 정보의 빈 항목을 병합합니다. 기존 명함을 덮어쓰거나 삭제하지 않습니다.\n• OCR 결과는 저장 전에 확인하세요. 사진과 인식은 기기 안에서 처리됩니다.").setPositiveButton("닫기",null).show();}
    private void setSort(int mode){sortMode=mode;getPreferences(MODE_PRIVATE).edit().putInt("sortMode",mode).apply();sortButton.setText(sortLabel());refresh();}
    private void showAddMenu(){new AlertDialog.Builder(this).setTitle("명함 추가").setItems(new String[]{"명함 촬영 · 자동 인식","직접 입력","기존 명함 가져오기"},(d,w)->{if(w==0)startActivity(new Intent(this,EditActivity.class).putExtra("scan",true));else if(w==1)startActivity(new Intent(this,EditActivity.class));else showImportMenu();}).show();}
    private void showManageMenu(){
        Dialog sheet=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(Ui.dp(this,12),Ui.dp(this,6),Ui.dp(this,12),Ui.dp(this,6));box.setBackground(Ui.rounded(Color.WHITE,20,this));
        LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);heading.addView(Ui.text(this,"명함 관리 · v2.5",20,true),Ui.weight(1));Button close=Ui.button(this,"닫기");heading.addView(close);box.addView(heading);close.setOnClickListener(v->sheet.dismiss());
        box.addView(Ui.label(this,"빠른 정렬 · 다시 누르면 역순"));LinearLayout sorts=new LinearLayout(this);String[] labels={"입력일","이름","회사"};int[] modes={sortMode==1?0:1,sortMode==2?3:2,sortMode==4?5:4};for(int i=0;i<3;i++){final int mode=modes[i];Button option=Ui.button(this,labels[i]);Ui.styleButton(option,i==0?(sortMode==0||sortMode==1):i==1?(sortMode==2||sortMode==3):(sortMode==4||sortMode==5));sorts.addView(option,Ui.weight(1));option.setOnClickListener(v->{sheet.dismiss();setSort(mode);});}box.addView(sorts);
        ScrollView scrolling=new ScrollView(this);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);scrolling.addView(actions);
        String[] names={"현재 목록 내보내기","전체 명함 내보내기","여러 명함 선택","그룹 관리","중복 명함 검토","기존 명함 가져오기","사진 포함 백업","글자 크기","전체 정렬 방식","사용 안내"};Runnable[] commands={()->exportMenu(new ArrayList<>(visibleItems)),()->exportMenu(db.search("",false,"",sortMode)),this::beginSelection,this::manageGroups,this::reviewDuplicates,this::showImportMenu,this::createBackup,this::chooseTextSize,this::chooseSort,this::showGuide};
        for(int i=0;i<names.length;i+=2){LinearLayout row=new LinearLayout(this);for(int j=i;j<Math.min(i+2,names.length);j++){final Runnable command=commands[j];Button action=Ui.button(this,names[j]);LinearLayout.LayoutParams lp=Ui.weight(1);lp.setMargins(Ui.dp(this,2),Ui.dp(this,2),Ui.dp(this,2),0);row.addView(action,lp);action.setOnClickListener(v->{sheet.dismiss();command.run();});}actions.addView(row);}box.addView(scrolling,new LinearLayout.LayoutParams(-1,0,1));sheet.setContentView(box);Window window=sheet.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setGravity(Gravity.BOTTOM);}sheet.show();if(window!=null)window.setLayout(-1,Math.min(Ui.dp(this,376),(int)(getResources().getDisplayMetrics().heightPixels*0.85f)));
    }
    private void showCardMenu(Contact card){if(selectionMode!=null){toggleSelected(card.id);return;}String phone=card.get("mobile1").isEmpty()?card.get("phone1"):card.get("mobile1");new AlertDialog.Builder(this).setTitle(card.get("name").isEmpty()?"명함":card.get("name")).setItems(new String[]{"상세 보기","정보 수정",card.favorite==1?"즐겨찾기 해제":"즐겨찾기 설정","그룹 지정","이 명함 내보내기","여러 명함 선택","전화 걸기","명함 삭제"},(d,w)->{switch(w){case 0:startActivity(new Intent(this,DetailActivity.class).putExtra("id",card.id));break;case 1:startActivity(new Intent(this,EditActivity.class).putExtra("id",card.id));break;case 2:db.setFavorite(card.id,card.favorite!=1);refresh();break;case 3:assignGroup(Collections.singletonList(card.id));break;case 4:exportMenu(Collections.singletonList(card));break;case 5:beginSelection();toggleSelected(card.id);break;case 6:if(phone.isEmpty())toast("전화번호가 없습니다.");else try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(phone))));}catch(Exception e){error(e);}break;case 7:new AlertDialog.Builder(this).setTitle("명함 삭제").setMessage("이 명함과 사용하지 않는 해당 사진을 삭제할까요?").setNegativeButton("취소",null).setPositiveButton("삭제",(x,y)->{db.deleteWithUnusedImages(card.id);refresh();}).show();break;}}).show();}
    private void chooseTextSize(){String[] labels={"기본", "크게", "아주 크게"};int current=getSharedPreferences("display",MODE_PRIVATE).getInt("size",0);new AlertDialog.Builder(this).setTitle("글자 크기").setSingleChoiceItems(labels,current,(d,w)->{getSharedPreferences("display",MODE_PRIVATE).edit().putInt("size",w).apply();d.dismiss();recreate();}).setNegativeButton("취소",null).show();}
    private void exportMenu(List<Contact> items){if(items.isEmpty()){toast("내보낼 명함이 없습니다.");return;}new AlertDialog.Builder(this).setTitle(items.size()+"명 내보내기 · 파일 형식").setItems(new String[]{"Excel (.xlsx) · 연락처 정보","CSV (.csv) · 연락처 정보","연락처 파일 (.vcf)","사진 포함 백업 (.zip)"},(d,w)->exportDestination(items,w)).setNegativeButton("취소",null).show();}
    private void exportDestination(List<Contact> items,int format){LinearLayout title=new LinearLayout(this);title.setOrientation(LinearLayout.VERTICAL);title.setPadding(Ui.dp(this,20),Ui.dp(this,16),Ui.dp(this,20),Ui.dp(this,8));title.addView(Ui.text(this,"내보내기 방법 · "+items.size()+"명",19,true));title.addView(Ui.text(this,"공유창에서 이메일·Quick Share·블루투스 등을 선택하세요. 공유 대상은 기기에 설치된 앱에 따라 표시됩니다.",13,false));new AlertDialog.Builder(this).setCustomTitle(title).setItems(new String[]{"휴대폰 / 폴더에 파일 저장","다른 앱으로 공유"},(d,w)->exportFile(items,format,w==1)).setNegativeButton("취소",null).show();}
    private void exportFile(List<Contact> items,int format,boolean share){
        ProgressDialog pd=ProgressDialog.show(this,"내보내기",items.size()+"명의 파일을 만들고 있습니다…",true,false);
        new Thread(()->{File created=null;try{
            String ext=format==0?".xlsx":format==1?".csv":format==2?".vcf":".zip";created=format==3?BackupManager.createBackup(this,items):ExportShare.newFile(this,"명함관리_LSI_"+items.size()+"명",ext);
            if(format==0)DataExchange.writeXlsx(created,items);else if(format==1)DataExchange.writeCsv(created,items);else if(format==2)DataExchange.writeVcard(created,items);
            final File out=created;runOnUiThread(()->{pd.dismiss();if(isFinishing()||isDestroyed())return;try{if(share)startActivity(ExportShare.chooser(this,out));else{pendingExport=out;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(getContentResolver().getType(CardFileProvider.uriFor(this,out)));i.putExtra(Intent.EXTRA_TITLE,out.getName());startActivityForResult(i,REQ_EXPORT);}}catch(Exception e){error(e);}});
        }catch(Exception e){if(created!=null)created.delete();runOnUiThread(()->{pd.dismiss();if(!isFinishing()&&!isDestroyed())error(e);});}}).start();
    }
    private void beginSelection(){if(selectionMode!=null)return;selectionMode=startActionMode(new ActionMode.Callback(){public boolean onCreateActionMode(ActionMode m,Menu menu){search.setEnabled(false);favButton.setEnabled(false);groupButton.setEnabled(false);sortButton.setEnabled(false);menu.add(0,1,0,"전체 선택");menu.add(0,2,1,"즐겨찾기 설정");menu.add(0,3,2,"즐겨찾기 해제");menu.add(0,4,3,"그룹 지정");menu.add(0,5,4,"내보내기");menu.add(0,6,5,"삭제");m.setTitle("명함을 선택하세요");return true;}public boolean onPrepareActionMode(ActionMode m,Menu menu){return false;}public void onDestroyActionMode(ActionMode m){selectionMode=null;selected.clear();search.setEnabled(true);favButton.setEnabled(true);groupButton.setEnabled(true);sortButton.setEnabled(true);refresh();}public boolean onActionItemClicked(ActionMode m,MenuItem item){int action=item.getItemId();if(action==1){if(selected.size()==visibleItems.size())selected.clear();else for(Contact x:visibleItems)selected.add(x.id);refresh();return true;}if(selected.isEmpty()){toast("명함을 먼저 선택하세요.");return true;}List<Long> ids=new ArrayList<>(selected);if(action==5){List<Contact> rows=new ArrayList<>();for(Contact x:visibleItems)if(selected.contains(x.id))rows.add(x);exportMenu(rows);}else if(action==4)assignGroup(ids);else if(action==6)new AlertDialog.Builder(MainActivity.this).setTitle(ids.size()+"명 삭제").setMessage("선택한 명함과 사용하지 않는 사진을 삭제합니다. 복구하려면 미리 저장한 백업이 필요합니다.").setNegativeButton("취소",null).setPositiveButton("삭제",(d,w)->{for(long id:ids)db.deleteWithUnusedImages(id);m.finish();refresh();}).show();else{android.database.sqlite.SQLiteDatabase sql=db.getWritableDatabase();sql.beginTransaction();try{for(long id:ids)db.setFavorite(id,action==2);sql.setTransactionSuccessful();}finally{sql.endTransaction();}m.finish();refresh();}return true;}});}
    private void toggleSelected(long id){if(!selected.add(id))selected.remove(id);refresh();}
    private void assignGroup(List<Long> ids){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(Ui.dp(this,16),0,Ui.dp(this,16),0);EditText input=Ui.edit(this,"그룹 이름 (비우면 분류 해제)");box.addView(input);Button choose=Ui.button(this,"기존 그룹 선택");box.addView(choose);choose.setOnClickListener(v->{List<String> names=db.groups();new AlertDialog.Builder(this).setItems(names.toArray(new String[0]),(d,w)->input.setText(names.get(w))).show();});new AlertDialog.Builder(this).setTitle(ids.size()+"명 그룹 지정").setView(box).setNegativeButton("취소",null).setPositiveButton("적용",(d,w)->{String group=input.getText().toString().trim();android.database.sqlite.SQLiteDatabase sql=db.getWritableDatabase();sql.beginTransaction();try{for(long id:ids)db.setGroup(id,group);sql.setTransactionSuccessful();}finally{sql.endTransaction();}if(selectionMode!=null)selectionMode.finish();refresh();}).show();}
    private void manageGroups(){List<String> names=db.groups();if(names.isEmpty()){toast("명함 수정 또는 여러 명함 선택에서 그룹 이름을 입력하세요.");return;}new AlertDialog.Builder(this).setTitle("관리할 그룹").setItems(names.toArray(new String[0]),(d,w)->{String old=names.get(w);EditText input=Ui.edit(this,"새 그룹 이름 (비우면 분류 해제)");input.setText(old);new AlertDialog.Builder(this).setTitle("그룹 이름 변경: "+old).setMessage("명함은 유지하고 그룹 분류만 변경합니다.").setView(input).setNegativeButton("취소",null).setPositiveButton("적용",(a,b)->{String name=input.getText().toString().trim();db.renameGroup(old,name);if(groupFilter.equals(old)){groupFilter=name;groupButton.setText("그룹: "+(name.isEmpty()?"전체":name));}refresh();}).show();}).show();}
    private void reviewDuplicates(){ProgressDialog pd=ProgressDialog.show(this,"중복 명함 검토","비슷한 명함을 찾고 있습니다…",true,false);new Thread(()->{try{List<Contact> rows=db.all();List<long[]> pairs=new ArrayList<>();List<String> labels=new ArrayList<>();outer:for(int i=0;i<rows.size();i++)for(int j=i+1;j<rows.size();j++)if(DbHelper.samePerson(rows.get(i),rows.get(j))){Contact a=rows.get(i),b=rows.get(j);pairs.add(new long[]{a.id,b.id});labels.add((a.get("name").isEmpty()?"(이름 없음)":a.get("name"))+" · "+a.get("company1")+"  (#"+a.id+" / #"+b.id+")");if(pairs.size()>=200)break outer;}runOnUiThread(()->{pd.dismiss();if(isFinishing()||isDestroyed())return;if(pairs.isEmpty()){toast("중복 후보가 없습니다.");return;}new AlertDialog.Builder(this).setTitle("중복 후보 "+pairs.size()+"쌍 · 선택하여 확인").setItems(labels.toArray(new String[0]),(d,w)->{long[] pair=pairs.get(w);Contact a=db.get(pair[0]),b=db.get(pair[1]);if(a==null||b==null)return;new AlertDialog.Builder(this).setTitle("두 명함 병합").setMessage("먼저 저장한 명함을 유지하고 빈 항목을 채웁니다. 서로 다른 정보는 메모에 보존합니다.\n\n"+duplicateSummary(a)+"\n\n"+duplicateSummary(b)).setNegativeButton("취소",null).setNeutralButton("두 번째 명함 보기",(x,y)->startActivity(new Intent(this,DetailActivity.class).putExtra("id",b.id))).setPositiveButton("병합",(x,y)->{try{db.mergeAndDelete(a.id,b.id);refresh();toast("병합 완료");}catch(Exception e){error(e);}}).show();}).setPositiveButton("닫기",null).show();});}catch(Exception e){runOnUiThread(()->{pd.dismiss();if(!isFinishing()&&!isDestroyed())error(e);});}}).start();}
    private String duplicateSummary(Contact c){return "#"+c.id+" "+c.get("name")+"\n"+c.get("company1")+" "+c.get("department1")+" "+c.get("title1")+"\n"+c.get("mobile1")+" "+c.get("email1");}

    private void showImportMenu(){new AlertDialog.Builder(this).setTitle("가져오기").setItems(new String[]{"CamCard Excel + 명함 사진 ZIP","CamCard / LSI Excel 가져오기","LSI 전체 백업 복원"},(d,w)->{camXlsx=null;if(w==0)pickFile(REQ_XLSX_ZIP,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","CamCard Excel 선택");else if(w==1)pickFile(REQ_XLSX_ONLY,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","CamCard Excel 선택");else pickFile(REQ_RESTORE,"application/zip","LSI 백업 ZIP 선택");}).show();}
    private void showBackupMenu(){new AlertDialog.Builder(this).setTitle("백업 / 복원").setItems(new String[]{"백업 / 내보내기 · 저장 또는 공유","백업 파일 복원"},(d,w)->{if(w==0)createBackup();else pickFile(REQ_RESTORE,"application/zip","LSI 백업 ZIP 선택");}).show();}
    private void pickFile(int req,String type,String title){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(type);i.putExtra(Intent.EXTRA_TITLE,title);startActivityForResult(i,req);}

    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{
        if(req==REQ_EXPORT){if(pendingExport!=null){BackupManager.copyFileToUri(this,pendingExport,uri);toast("내보내기 완료");pendingExport=null;}}
        else if(req==REQ_XLSX_ZIP){camXlsx=BackupManager.copyUriToCache(this,uri,"camcard_import.xlsx");pickFile(REQ_ZIP,"application/zip","CamCard 명함 사진 ZIP 선택");}
        else if(req==REQ_XLSX_ONLY){camXlsx=BackupManager.copyUriToCache(this,uri,"camcard_import.xlsx");runCamCardImport(null);}
        else if(req==REQ_ZIP){File z=BackupManager.copyUriToCache(this,uri,"camcard_images.zip");runCamCardImport(z);}
        else if(req==REQ_SAVE_BACKUP){if(pendingBackup!=null){BackupManager.copyFileToUri(this,pendingBackup,uri);toast("백업 저장 완료");}}
        else if(req==REQ_RESTORE){File f=BackupManager.copyUriToCache(this,uri,"lsi_restore.zip");runRestore(f);}
    }catch(Exception e){error(e);}}

    private void runCamCardImport(File zip){if(camXlsx==null)return;ProgressDialog pd=ProgressDialog.show(this,"CamCard 가져오기","명함 정보를 확인하고 있습니다…",true,false);new Thread(()->{try{CamCardImporter.Result r=CamCardImporter.importFiles(this,camXlsx,zip,db);runOnUiThread(()->{pd.dismiss();refresh();new AlertDialog.Builder(this).setTitle("CamCard 가져오기 완료").setMessage(r.message()).setPositiveButton("확인",null).show();});}catch(Exception e){runOnUiThread(()->{pd.dismiss();error(e);});}}).start();}
    private void createBackup(){exportDestination(db.all(),3);}
    private void runRestore(File f){ProgressDialog pd=ProgressDialog.show(this,"백업 복원","중복 명함을 확인하며 복원하고 있습니다…",true,false);new Thread(()->{try{BackupManager.RestoreResult r=BackupManager.restoreBackup(this,f,db);runOnUiThread(()->{pd.dismiss();refresh();toast(r.message());});}catch(Exception e){runOnUiThread(()->{pd.dismiss();error(e);});}}).start();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void error(Exception e){new AlertDialog.Builder(this).setTitle("작업 실패").setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("확인",null).show();}

    private interface CardMenu{void show(Contact card);}
    private static class ContactAdapter extends BaseAdapter {
        private final Context c;private final List<Contact> items;private final Set<Long> selected;private final CardMenu menu;ContactAdapter(Context c,List<Contact>x,Set<Long>s,CardMenu menu){this.c=c;items=x;this.selected=s;this.menu=menu;}
        public int getCount(){return items.size();}public Object getItem(int p){return items.get(p);}public long getItemId(int p){return items.get(p).id;}
        public View getView(int p,View old,ViewGroup parent){Contact x=items.get(p);LinearLayout row=new LinearLayout(c);row.setOrientation(LinearLayout.HORIZONTAL);row.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(Ui.dp(c,8),Ui.dp(c,8),Ui.dp(c,8),Ui.dp(c,8));row.setBackgroundColor(selected.contains(x.id)?Color.rgb(220,239,255):Color.WHITE);
            ImageView im=new ImageView(c);im.setScaleType(ImageView.ScaleType.FIT_CENTER);String path=!x.get("image_front").isEmpty()?x.get("image_front"):x.get("image_back");Bitmap bm=ImageUtil.thumbnail(path,240);if(bm!=null)im.setImageBitmap(bm);else{im.setBackgroundColor(Color.rgb(232,235,239));im.setImageResource(android.R.drawable.ic_menu_gallery);}row.addView(im,new LinearLayout.LayoutParams(Ui.dp(c,80),Ui.dp(c,52)));
            LinearLayout texts=new LinearLayout(c);texts.setOrientation(LinearLayout.VERTICAL);texts.setPadding(Ui.dp(c,10),0,0,0);TextView name=Ui.text(c,(x.favorite==1?"★ ":"")+nz(x.get("name"),"(이름 없음)"),18,true);Ui.compactText(name,1);texts.addView(name);String sub=join(" · ",x.get("company1"),x.get("department1"),x.get("title1"));TextView company=Ui.text(c,sub,14,false);Ui.compactText(company,2);company.setTextColor(Color.rgb(84,93,103));if(!sub.isEmpty())texts.addView(company);String phone=nz(x.get("mobile1"),x.get("phone1"));TextView number=Ui.text(c,PhoneDisplay.format(phone),15,false);Ui.compactText(number,1);if(!phone.isEmpty())texts.addView(number);String created=x.get("created_at");if(!created.isEmpty()){String date=created.length()>=10?created.substring(0,10):created;TextView saved=Ui.text(c,"등록일 "+date,11,false);Ui.compactText(saved,1);saved.setTextColor(Color.rgb(125,134,145));texts.addView(saved);}row.setMinimumHeight(Ui.dp(c,80));row.addView(texts,new LinearLayout.LayoutParams(0,-2,1));Button more=Ui.button(c,selected.contains(x.id)?"✓":"⋮");more.setFocusable(false);more.setFocusableInTouchMode(false);more.setContentDescription(nz(x.get("name"),"명함")+" 빠른 메뉴");more.setTextSize(20);more.setPadding(0,0,0,0);more.setBackgroundColor(Color.TRANSPARENT);row.addView(more,new LinearLayout.LayoutParams(Ui.dp(c,48),Ui.dp(c,48)));more.setOnClickListener(v->menu.show(x));return row;}
        static String nz(String a,String b){return a==null||a.isEmpty()?b:a;}static String join(String sep,String...s){StringBuilder b=new StringBuilder();for(String x:s)if(x!=null&&!x.isEmpty()){if(b.length()>0)b.append(sep);b.append(x);}return b.toString();}
    }
}
