package com.lsi.businesscard;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.activity.ComponentActivity;
import androidx.camera.core.*;
import androidx.camera.lifecycle.ProcessCameraProvider;
import androidx.camera.view.PreviewView;
import androidx.core.content.ContextCompat;
import java.io.*;
import java.nio.ByteBuffer;
import java.util.concurrent.*;
/** App-owned camera screen, with live contour overlay and deliberate fallback choices. */
public class ScanActivity extends ComponentActivity {
    private PreviewView preview;private EdgeOverlay overlay;private TextView guide;private Button flash,autoMode,manualMode,shutter;private ImageCapture capture;private androidx.camera.core.Camera camera;private ProcessCameraProvider provider;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean manual,busy;private boolean torch;private volatile long lastFrame;private long stableSince;private float[] lastCorners;private float previousMean=-1;private int stableCount;
    @Override public void onCreate(Bundle state){super.onCreate(state);manual=state==null?ScanSettings.manual(this):state.getBoolean("manual");
        LinearLayout page=new LinearLayout(this);page.setOrientation(1);page.setBackgroundColor(Color.rgb(21,25,31));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);
        Button close=control("✕");close.setContentDescription("촬영 취소");close.setOnClickListener(v->finish());top.addView(close,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));
        TextView title=Ui.text(this,"명함 촬영",17,true);title.setTextColor(Color.WHITE);title.setGravity(Gravity.CENTER);top.addView(title,Ui.weight(1));
        flash=control("플래시 끔");flash.setTextSize(11);top.addView(flash);flash.setOnClickListener(v->{if(camera!=null&&camera.getCameraInfo().hasFlashUnit()){torch=!torch;camera.getCameraControl().enableTorch(torch);flash.setText(torch?"플래시 켬":"플래시 끔");flash.setContentDescription(flash.getText());}else toast("이 카메라는 플래시를 지원하지 않습니다.");});
        Button help=control("ⓘ");help.setContentDescription("촬영 도움말");top.addView(help,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));help.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("촬영 도움말").setMessage("명함을 평평하게 두고 빛 반사를 피해 주세요. 화면을 누르면 초점을 맞춥니다. 파란 테두리는 발견한 명함, 초록 테두리는 촬영 준비 상태입니다. 자동 모드에서는 안정되면 촬영하며, 수동 모드에서는 촬영 버튼을 누르세요. 촬영 후 네 모서리를 수정할 수 있습니다.").setItems(new String[]{"Google 스캐너 사용"},(d,w)->google()).setNegativeButton("닫기",null).show());page.addView(top);
        FrameLayout frame=new FrameLayout(this);preview=new PreviewView(this);preview.setImplementationMode(PreviewView.ImplementationMode.COMPATIBLE);preview.setScaleType(PreviewView.ScaleType.FILL_CENTER);frame.addView(preview,new FrameLayout.LayoutParams(-1,-1));overlay=new EdgeOverlay();frame.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
        guide=Ui.text(this,"명함을 화면 중앙에 맞춰주세요",12,false);guide.setTextColor(Color.WHITE);guide.setGravity(Gravity.CENTER);guide.setPadding(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,8));guide.setBackground(Ui.rounded(0xB321252B,18,this));FrameLayout.LayoutParams hint=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL);hint.topMargin=Ui.dp(this,12);hint.leftMargin=hint.rightMargin=Ui.dp(this,12);frame.addView(guide,hint);page.addView(frame,new LinearLayout.LayoutParams(-1,0,1));
        preview.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP&&camera!=null){MeteringPoint point=preview.getMeteringPointFactory().createPoint(e.getX(),e.getY());camera.getCameraControl().startFocusAndMetering(new FocusMeteringAction.Builder(point,FocusMeteringAction.FLAG_AF|FocusMeteringAction.FLAG_AE).setAutoCancelDuration(3,TimeUnit.SECONDS).build());v.performClick();}return true;});
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,Ui.dp(this,8),0,0);
        Button gallery=new Button(this){private final Paint icon=new Paint(Paint.ANTI_ALIAS_FLAG);@Override protected void onDraw(Canvas canvas){super.onDraw(canvas);float x=getWidth()/2f,y=getHeight()/2f,d=Ui.dp(getContext(),11);icon.setColor(Color.WHITE);icon.setStyle(Paint.Style.STROKE);icon.setStrokeWidth(Ui.dp(getContext(),2));canvas.drawRoundRect(x-d,y-d,x+d,y+d,3,3,icon);Path mountain=new Path();mountain.moveTo(x-d+3,y+d-3);mountain.lineTo(x-2,y-1);mountain.lineTo(x+3,y+3);mountain.lineTo(x+6,y-2);mountain.lineTo(x+d-3,y+d-3);canvas.drawPath(mountain,icon);canvas.drawCircle(x+5,y-5,2,icon);}};gallery.setBackgroundColor(Color.TRANSPARENT);gallery.setElevation(0);gallery.setStateListAnimator(null);gallery.setContentDescription("사진 선택");row.addView(gallery,new LinearLayout.LayoutParams(0,Ui.dp(this,72),1));gallery.setOnClickListener(v->pick());
        shutter=new Button(this){private final Paint ring=new Paint(Paint.ANTI_ALIAS_FLAG);@Override protected void onDraw(Canvas canvas){super.onDraw(canvas);float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(cx,cy)-Ui.dp(getContext(),5);ring.setColor(isEnabled()?Color.WHITE:Color.LTGRAY);ring.setStyle(Paint.Style.STROKE);ring.setStrokeWidth(Ui.dp(getContext(),3));canvas.drawCircle(cx,cy,r,ring);ring.setStyle(Paint.Style.FILL);canvas.drawCircle(cx,cy,r-Ui.dp(getContext(),8),ring);}};shutter.setText("");shutter.setBackgroundColor(Color.TRANSPARENT);shutter.setElevation(0);shutter.setStateListAnimator(null);shutter.setContentDescription("명함 촬영 버튼");row.addView(shutter,new LinearLayout.LayoutParams(Ui.dp(this,80),Ui.dp(this,80)));shutter.setOnClickListener(v->take());View balance=new View(this);row.addView(balance,new LinearLayout.LayoutParams(0,Ui.dp(this,72),1));page.addView(row);
        LinearLayout choices=new LinearLayout(this);choices.setGravity(Gravity.CENTER);autoMode=control("자동");manualMode=control("수동");choices.addView(autoMode,new LinearLayout.LayoutParams(Ui.dp(this,96),Ui.dp(this,48)));choices.addView(manualMode,new LinearLayout.LayoutParams(Ui.dp(this,96),Ui.dp(this,48)));autoMode.setOnClickListener(v->selectMode(false));manualMode.setOnClickListener(v->selectMode(true));page.addView(choices);page.setPadding(0,0,0,Ui.dp(this,12));updateMode();Ui.setContentView(this,page,true);
        if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)preview.post(this::startCamera);else requestPermissions(new String[]{Manifest.permission.CAMERA},1);
    }
    private Button control(String text){Button b=Ui.button(this,text);b.setTextColor(Color.WHITE);b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private void selectMode(boolean value){manual=value;ScanSettings.setManual(this,manual);updateMode();}
    private void updateMode(){Button[] buttons={autoMode,manualMode};for(int i=0;i<2;i++){boolean selected=i==(manual?1:0);buttons[i].setSelected(selected);buttons[i].setTextColor(selected?Color.WHITE:Color.LTGRAY);buttons[i].setBackground(Ui.rounded(selected?Color.rgb(25,118,210):Color.rgb(46,50,57),24,this));buttons[i].setContentDescription((i==0?"자동 촬영":"수동 촬영")+(selected?" 선택됨":""));}}
    private void startCamera(){if(isFinishing()||isDestroyed())return;com.google.common.util.concurrent.ListenableFuture<ProcessCameraProvider> future=ProcessCameraProvider.getInstance(this);future.addListener(()->{if(isFinishing()||isDestroyed())return;try{provider=future.get();Preview use=new Preview.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3).build();capture=new ImageCapture.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3).setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).setTargetRotation(preview.getDisplay().getRotation()).build();ImageAnalysis analysis=new ImageAnalysis.Builder().setTargetResolution(new android.util.Size(640,480)).setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();analysis.setTargetRotation(preview.getDisplay().getRotation());analysis.setAnalyzer(worker,this::analyze);use.setSurfaceProvider(preview.getSurfaceProvider());provider.unbindAll();try{UseCaseGroup.Builder group=new UseCaseGroup.Builder().addUseCase(use).addUseCase(capture).addUseCase(analysis);ViewPort viewport=preview.getViewPort();if(viewport!=null)group.setViewPort(viewport);camera=provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,group.build());}catch(Exception e){analysis.clearAnalyzer();UseCaseGroup.Builder fallback=new UseCaseGroup.Builder().addUseCase(use).addUseCase(capture);if(preview.getViewPort()!=null)fallback.setViewPort(preview.getViewPort());camera=provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,fallback.build());guide.setText("이 기기에서는 수동 촬영을 사용하세요");manual=true;updateMode();}flash.setEnabled(camera.getCameraInfo().hasFlashUnit());}catch(Exception e){guide.setText("카메라를 열 수 없습니다. 사진 선택 또는 Google 스캐너를 사용하세요.");shutter.setEnabled(false);}},ContextCompat.getMainExecutor(this));}
    private void analyze(ImageProxy image){Bitmap bitmap=null;try{long now=SystemClock.elapsedRealtime();if(busy||now-lastFrame<220)return;lastFrame=now;ImageProxy.PlaneProxy plane=image.getPlanes()[0];ByteBuffer data=plane.getBuffer();Rect crop=image.getCropRect();int w=crop.width(),h=crop.height(),stride=plane.getRowStride(),step=plane.getPixelStride();int[] pixels=new int[w*h];double mean=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++){int index=data.position()+(y+crop.top)*stride+(x+crop.left)*step;int value=data.get(index)&255;pixels[y*w+x]=Color.rgb(value,value,value);mean+=value;}mean/=pixels.length;bitmap=Bitmap.createBitmap(pixels,w,h,Bitmap.Config.ARGB_8888);int rotation=image.getImageInfo().getRotationDegrees();if(rotation!=0){Matrix m=new Matrix();m.postRotate(rotation);Bitmap rotated=Bitmap.createBitmap(bitmap,0,0,w,h,m,true);bitmap.recycle();bitmap=rotated;}CardEdges.Detection result=CardEdges.detect(bitmap);float[] q=result.corners;boolean stable=q!=null&&result.sharpness>65&&CardEdges.movement(lastCorners,q)<.018f&&previousMean>=0&&Math.abs(mean-previousMean)<5;previousMean=(float)mean;lastCorners=q;if(stable){if(stableCount++==0)stableSince=now;}else{stableCount=0;stableSince=0;}boolean fire=stable&&stableCount>=4&&now-stableSince>1100;final int fw=bitmap.getWidth(),fh=bitmap.getHeight();runOnUiThread(()->{if(isFinishing()||isDestroyed()||busy)return;overlay.set(q,fw,fh,stable);guide.setText(q==null?"명함을 화면 중앙에 맞춰주세요":manual?"외곽선을 확인하고 촬영 버튼을 누르세요":fire?"촬영합니다":"명함을 찾았습니다. 잠시 움직이지 마세요");if(fire&&!manual)take();});}catch(Exception ignored){}finally{if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();image.close();}}
    void take(){if(busy||capture==null)return;busy=true;shutter.setEnabled(false);stableCount=0;try{File file=CardFileProvider.newCameraFile(this,"native");capture.takePicture(new ImageCapture.OutputFileOptions.Builder(file).build(),ContextCompat.getMainExecutor(this),new ImageCapture.OnImageSavedCallback(){public void onImageSaved(ImageCapture.OutputFileResults result){if(isFinishing()||isDestroyed()){file.delete();return;}try{String path=ImageUtil.copyFileToCards(ScanActivity.this,file,"capture");file.delete();setResult(RESULT_OK,new Intent().putExtra("path",path));finish();}catch(Exception e){file.delete();failed(e);}}public void onError(ImageCaptureException e){file.delete();failed(e);}});}catch(Exception e){failed(e);}}
    private void failed(Exception e){busy=false;shutter.setEnabled(true);guide.setText("촬영 실패. 다시 촬영하거나 사진을 선택하세요.");toast(e.getMessage());}
    private void pick(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),2);}
    private void google(){busy=true;if(provider!=null)provider.unbindAll();DocumentScan.launch(this,3,()->true,error->{busy=false;startCamera();toast("Google 스캐너를 열 수 없습니다. 직접 촬영 또는 사진 선택을 사용하세요.");});}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK){busy=false;startCamera();return;}try{android.net.Uri uri=req==3?DocumentScan.image(data):data==null?null:data.getData();if(uri==null)return;String path=ImageUtil.copyUriToCards(this,uri,"scan_import");setResult(RESULT_OK,new Intent().putExtra("path",path));finish();}catch(Exception e){failed(e);}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==1&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startCamera();else if(request==1){guide.setText("카메라 권한이 필요합니다. 사진 선택은 사용할 수 있습니다.");shutter.setEnabled(false);}}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putBoolean("manual",manual);}
    @Override protected void onDestroy(){if(provider!=null)provider.unbindAll();worker.shutdown();super.onDestroy();}
    boolean cameraReady(){return capture!=null&&camera!=null&&lastFrame>0;}
    private void toast(String s){Toast.makeText(this,s==null?"촬영 오류":s,Toast.LENGTH_LONG).show();}
    private final class EdgeOverlay extends View {
        private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private float[] q;private int iw=1,ih=1;private boolean ready;
        EdgeOverlay(){super(ScanActivity.this);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
        void set(float[] corners,int w,int h,boolean stable){q=corners;iw=w;ih=h;ready=stable;invalidate();}
        protected void onDraw(Canvas canvas){paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Ui.dp(getContext(),2));
            if(q==null){paint.setColor(0x88FFFFFF);float width=getWidth()*.8f,height=Math.min(getHeight()*.6f,width/1.58f),cx=getWidth()/2f,cy=getHeight()/2f;paint.setPathEffect(new DashPathEffect(new float[]{Ui.dp(getContext(),12),Ui.dp(getContext(),8)},0));canvas.drawRoundRect(cx-width/2,cy-height/2,cx+width/2,cy+height/2,Ui.dp(getContext(),8),Ui.dp(getContext(),8),paint);paint.setPathEffect(null);return;}
            float scale=Math.max(getWidth()/(float)iw,getHeight()/(float)ih),left=(getWidth()-iw*scale)/2,top=(getHeight()-ih*scale)/2;Path path=new Path();for(int i=0;i<4;i++){float x=left+q[i*2]*iw*scale,y=top+q[i*2+1]*ih*scale;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}path.close();paint.setColor(ready?Color.rgb(72,215,133):Color.rgb(64,180,245));canvas.drawPath(path,paint);
        }
    }
}
