package com.lsi.businesscard;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.activity.ComponentActivity;
import androidx.camera.core.*;
import androidx.camera.lifecycle.ProcessCameraProvider;
import androidx.camera.view.PreviewView;
import androidx.core.content.ContextCompat;
import java.io.*;
import java.nio.ByteBuffer;
import java.util.concurrent.*;
/** App-owned camera screen, with live contour overlay and deliberate fallback choices. */
public class ScanActivity extends ComponentActivity {
    private PreviewView preview;private EdgeOverlay overlay;private TextView guide;private Button flash,mode,shutter;private ImageCapture capture;private androidx.camera.core.Camera camera;private ProcessCameraProvider provider;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean manual,busy;private boolean torch;private long lastFrame,stableSince;private float[] lastCorners;private float previousMean=-1;private int stableCount;
    @Override public void onCreate(Bundle state){super.onCreate(state);manual=state==null?ScanSettings.manual(this):state.getBoolean("manual");
        LinearLayout page=new LinearLayout(this);page.setOrientation(1);page.setBackgroundColor(Color.rgb(21,25,31));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button close=control("✕");close.setContentDescription("촬영 취소");close.setOnClickListener(v->finish());top.addView(close,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));TextView title=Ui.text(this,"명함 촬영",18,true);title.setTextColor(Color.WHITE);title.setGravity(Gravity.CENTER);top.addView(title,Ui.weight(1));flash=control("플래시");flash.setTextSize(12);top.addView(flash);flash.setOnClickListener(v->{if(camera!=null&&camera.getCameraInfo().hasFlashUnit()){torch=!torch;camera.getCameraControl().enableTorch(torch);flash.setText(torch?"플래시 켬":"플래시 끔");}else toast("이 카메라는 플래시를 지원하지 않습니다.");});page.addView(top);
        FrameLayout frame=new FrameLayout(this);preview=new PreviewView(this);preview.setImplementationMode(PreviewView.ImplementationMode.COMPATIBLE);preview.setScaleType(PreviewView.ScaleType.FIT_CENTER);frame.addView(preview,new FrameLayout.LayoutParams(-1,-1));overlay=new EdgeOverlay();frame.addView(overlay,new FrameLayout.LayoutParams(-1,-1));page.addView(frame,new LinearLayout.LayoutParams(-1,0,1));
        preview.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP&&camera!=null){MeteringPoint point=preview.getMeteringPointFactory().createPoint(e.getX(),e.getY());camera.getCameraControl().startFocusAndMetering(new FocusMeteringAction.Builder(point,FocusMeteringAction.FLAG_AF|FocusMeteringAction.FLAG_AE).setAutoCancelDuration(3,TimeUnit.SECONDS).build());v.performClick();}return true;});
        guide=Ui.text(this,"명함 전체가 화면에 들어오도록 맞춰주세요",12,false);guide.setTextColor(Color.WHITE);guide.setGravity(Gravity.CENTER);guide.setPadding(Ui.dp(this,8),Ui.dp(this,4),Ui.dp(this,8),Ui.dp(this,4));page.addView(guide);
        mode=control("");mode.setTextSize(13);updateMode();mode.setOnClickListener(v->{manual=!manual;ScanSettings.setManual(this,manual);stableCount=0;stableSince=0;updateMode();});page.addView(mode);
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);Button gallery=control("사진 선택");gallery.setTextSize(12);row.addView(gallery,new LinearLayout.LayoutParams(0,Ui.dp(this,64),1));gallery.setOnClickListener(v->pick());shutter=new Button(this){private final Paint ring=new Paint(Paint.ANTI_ALIAS_FLAG);@Override protected void onDraw(Canvas canvas){super.onDraw(canvas);float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(cx,cy)-Ui.dp(getContext(),5);ring.setColor(isEnabled()?Color.WHITE:Color.LTGRAY);ring.setStyle(Paint.Style.STROKE);ring.setStrokeWidth(Ui.dp(getContext(),3));canvas.drawCircle(cx,cy,r,ring);ring.setStyle(Paint.Style.FILL);canvas.drawCircle(cx,cy,r-Ui.dp(getContext(),8),ring);}};shutter.setText("");shutter.setBackgroundColor(Color.TRANSPARENT);shutter.setElevation(0);shutter.setStateListAnimator(null);shutter.setContentDescription("명함 촬영 버튼");row.addView(shutter,new LinearLayout.LayoutParams(Ui.dp(this,76),Ui.dp(this,76)));shutter.setOnClickListener(v->take());Button more=control("도움말");more.setTextSize(12);row.addView(more,new LinearLayout.LayoutParams(0,Ui.dp(this,64),1));more.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("촬영 도움말").setMessage("명함을 평평하게 두고 빛 반사를 피해 주세요. 파란 외곽선이 안정되면 자동 촬영합니다. 촬영 후 네 모서리를 수정할 수 있습니다.").setItems(new String[]{"Google 스캐너 사용"},(d,w)->google()).setNegativeButton("닫기",null).show());page.addView(row);Ui.setContentView(this,page);
        if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)preview.post(this::startCamera);else requestPermissions(new String[]{Manifest.permission.CAMERA},1);
    }
    private Button control(String text){Button b=Ui.button(this,text);b.setTextColor(Color.WHITE);b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private void updateMode(){mode.setText(manual?"수동 촬영  ·  자동 촬영으로 전환":"자동 촬영  ·  수동 촬영으로 전환");mode.setContentDescription(manual?"수동 촬영 모드":"자동 촬영 모드");}
    private void startCamera(){if(isFinishing()||isDestroyed())return;com.google.common.util.concurrent.ListenableFuture<ProcessCameraProvider> future=ProcessCameraProvider.getInstance(this);future.addListener(()->{if(isFinishing()||isDestroyed())return;try{provider=future.get();Preview use=new Preview.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3).build();capture=new ImageCapture.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3).setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).setTargetRotation(preview.getDisplay().getRotation()).build();ImageAnalysis analysis=new ImageAnalysis.Builder().setTargetResolution(new android.util.Size(640,480)).setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();analysis.setAnalyzer(worker,this::analyze);use.setSurfaceProvider(preview.getSurfaceProvider());provider.unbindAll();try{camera=provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,use,capture,analysis);}catch(Exception e){analysis.clearAnalyzer();camera=provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,use,capture);guide.setText("이 기기에서는 수동 촬영을 사용하세요");manual=true;updateMode();}flash.setEnabled(camera.getCameraInfo().hasFlashUnit());}catch(Exception e){guide.setText("카메라를 열 수 없습니다. 사진 선택 또는 Google 스캐너를 사용하세요.");shutter.setEnabled(false);}},ContextCompat.getMainExecutor(this));}
    private void analyze(ImageProxy image){Bitmap bitmap=null;try{long now=SystemClock.elapsedRealtime();if(busy||now-lastFrame<220)return;lastFrame=now;ImageProxy.PlaneProxy plane=image.getPlanes()[0];ByteBuffer data=plane.getBuffer();int w=image.getWidth(),h=image.getHeight(),stride=plane.getRowStride(),step=plane.getPixelStride();int[] pixels=new int[w*h];double mean=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++){int index=data.position()+y*stride+x*step;int value=data.get(index)&255;pixels[y*w+x]=Color.rgb(value,value,value);mean+=value;}mean/=pixels.length;bitmap=Bitmap.createBitmap(pixels,w,h,Bitmap.Config.ARGB_8888);int rotation=image.getImageInfo().getRotationDegrees();if(rotation!=0){Matrix m=new Matrix();m.postRotate(rotation);Bitmap rotated=Bitmap.createBitmap(bitmap,0,0,w,h,m,true);bitmap.recycle();bitmap=rotated;}CardEdges.Detection result=CardEdges.detect(bitmap);float[] q=result.corners;boolean stable=q!=null&&result.sharpness>65&&CardEdges.movement(lastCorners,q)<.018f&&previousMean>=0&&Math.abs(mean-previousMean)<5;previousMean=(float)mean;lastCorners=q;if(stable){if(stableCount++==0)stableSince=now;}else{stableCount=0;stableSince=0;}boolean fire=stable&&stableCount>=4&&now-stableSince>1100;final int fw=bitmap.getWidth(),fh=bitmap.getHeight();runOnUiThread(()->{if(isFinishing()||isDestroyed()||busy)return;overlay.set(q,fw,fh);guide.setText(q==null?"명함 전체가 화면에 들어오도록 맞춰주세요":manual?"외곽선을 확인하고 촬영 버튼을 누르세요":fire?"촬영합니다":"명함을 찾았습니다. 잠시 움직이지 마세요");if(fire&&!manual)take();});}catch(Exception ignored){}finally{if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();image.close();}}
    void take(){if(busy||capture==null)return;busy=true;shutter.setEnabled(false);stableCount=0;try{File file=CardFileProvider.newCameraFile(this,"native");capture.takePicture(new ImageCapture.OutputFileOptions.Builder(file).build(),ContextCompat.getMainExecutor(this),new ImageCapture.OnImageSavedCallback(){public void onImageSaved(ImageCapture.OutputFileResults result){if(isFinishing()||isDestroyed()){file.delete();return;}try{String path=ImageUtil.copyFileToCards(ScanActivity.this,file,"capture");file.delete();setResult(RESULT_OK,new Intent().putExtra("path",path));finish();}catch(Exception e){file.delete();failed(e);}}public void onError(ImageCaptureException e){file.delete();failed(e);}});}catch(Exception e){failed(e);}}
    private void failed(Exception e){busy=false;shutter.setEnabled(true);guide.setText("촬영 실패. 다시 촬영하거나 사진을 선택하세요.");toast(e.getMessage());}
    private void pick(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),2);}
    private void google(){busy=true;if(provider!=null)provider.unbindAll();DocumentScan.launch(this,3,()->true,error->{busy=false;startCamera();toast("Google 스캐너를 열 수 없습니다. 직접 촬영 또는 사진 선택을 사용하세요.");});}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK){busy=false;startCamera();return;}try{android.net.Uri uri=req==3?DocumentScan.image(data):data==null?null:data.getData();if(uri==null)return;String path=ImageUtil.copyUriToCards(this,uri,"scan_import");setResult(RESULT_OK,new Intent().putExtra("path",path));finish();}catch(Exception e){failed(e);}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==1&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startCamera();else if(request==1){guide.setText("카메라 권한이 필요합니다. 사진 선택은 사용할 수 있습니다.");shutter.setEnabled(false);}}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putBoolean("manual",manual);}
    @Override protected void onDestroy(){if(provider!=null)provider.unbindAll();worker.shutdown();super.onDestroy();}
    boolean cameraReady(){return capture!=null&&camera!=null;}
    private void toast(String s){Toast.makeText(this,s==null?"촬영 오류":s,Toast.LENGTH_LONG).show();}
    private final class EdgeOverlay extends View {private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private float[] q;private int iw=1,ih=1;EdgeOverlay(){super(ScanActivity.this);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}void set(float[] q,int w,int h){this.q=q;this.iw=w;this.ih=h;invalidate();}protected void onDraw(Canvas c){if(q==null)return;float scale=Math.min(getWidth()/(float)iw,getHeight()/(float)ih),left=(getWidth()-iw*scale)/2,top=(getHeight()-ih*scale)/2;Path path=new Path();for(int i=0;i<4;i++){float x=left+q[i*2]*iw*scale,y=top+q[i*2+1]*ih*scale;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}path.close();paint.setColor(Color.rgb(64,180,245));paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Ui.dp(getContext(),2));c.drawPath(path,paint);}}
}
