import com.lsi.businesscard.CardDetector;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.Arrays;

/** Exercises tilted, portrait, dark and textured cards, plus backgrounds that must not trigger capture. */
public class CameraDetectorChecks {
    static void check(boolean value,String text){if(!value)throw new AssertionError(text);}
    static byte[] gray(BufferedImage image){byte[] out=new byte[image.getWidth()*image.getHeight()];for(int y=0;y<image.getHeight();y++)for(int x=0;x<image.getWidth();x++){int c=image.getRGB(x,y);out[y*image.getWidth()+x]=(byte)(((c>>16&255)*77+(c>>8&255)*150+(c&255)*29)>>8);}return out;}
    static void card(int background,int foreground,boolean texture,int[] xs,int[] ys){int w=420,h=315;BufferedImage image=new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);Graphics2D g=image.createGraphics();g.setColor(new Color(background,background,background));g.fillRect(0,0,w,h);if(texture){g.setColor(new Color(Math.min(255,background+12),Math.min(255,background+12),Math.min(255,background+12)));for(int y=0;y<h;y+=7)g.drawLine(0,y,w,y+2);}g.setColor(new Color(foreground,foreground,foreground));g.fillPolygon(xs,ys,4);g.setColor(foreground>background?Color.DARK_GRAY:Color.WHITE);g.setFont(new Font("SansSerif",Font.PLAIN,15));g.drawString("LSI BUSINESS CARD",130,128);g.drawString("Name: Test User",130,151);g.drawString("010-1234-5678",130,175);g.dispose();CardDetector.Result found=CardDetector.detect(gray(image),w,h);check(found!=null,"missed card "+background+"/"+foreground+" texture="+texture);float[] expected=new float[8];for(int i=0;i<4;i++){expected[i*2]=xs[i]/(float)(w-1);expected[i*2+1]=ys[i]/(float)(h-1);}check(CardDetector.drift(found.corners,CardDetector.order(expected))<.045,"corner drift: "+Arrays.toString(found.corners));check(found.area>.15,"card area");System.out.println("PASS card "+background+"/"+foreground+" texture="+texture);}
    public static void main(String[] args){int[] x={88,336,352,72},y={81,67,214,227};card(50,240,false,x,y);card(160,240,true,x,y);card(230,35,false,x,y);card(55,200,false,new int[]{160,295,278,144},new int[]{43,51,264,251});byte[] flat=new byte[420*315];Arrays.fill(flat,(byte)125);check(CardDetector.detect(flat,420,315)==null,"flat surface triggers capture");byte[] stripes=flat.clone();for(int yy=0;yy<315;yy++)for(int xx=0;xx<420;xx++)stripes[yy*420+xx]=(byte)((xx/5)%2==0?180:70);check(CardDetector.detect(stripes,420,315)==null,"striped surface triggers capture");float[] p={.1f,.2f,.7f,.15f,.8f,.6f,.08f,.65f};float[] turned=p;for(int i=0;i<4;i++)turned=CardDetector.rotate(turned,90);check(CardDetector.drift(turned,CardDetector.order(p))<.0001,"rotation round trip");System.out.println("ALL_DETECTOR_CHECKS_PASSED");}
}
