package com.lsi.businesscard;
import android.app.*;
import android.content.*;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.*;
import android.media.ExifInterface;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

/** Runs against real Android SQLite, XML, graphics and Activity implementations. */
public class AppChecks extends Instrumentation {
    private void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    @Override public void onCreate(Bundle args){super.onCreate(args);start();}
    @Override public void onStart(){Bundle result=new Bundle();try{runChecks();result.putString("stream","\nALL_CHECKS_PASSED\n");finish(Activity.RESULT_OK,result);}catch(Throwable e){StringWriter w=new StringWriter();e.printStackTrace(new PrintWriter(w));result.putString("stream","\nCHECKS_FAILED\n"+w);finish(Activity.RESULT_CANCELED,result);}}
    private Contact card(String name,String company,String phone){Contact c=new Contact();c.put("name",name);c.put("company1",company);c.put("mobile1",phone);c.put("created_at","2026-10-08 09:00:00");c.put("updated_at","2026-10-08 09:00:00");return c;}
    private void runChecks()throws Exception{
        Context ctx=getTargetContext();ctx.deleteDatabase(DbHelper.DB_NAME);
        SQLiteDatabase old=ctx.openOrCreateDatabase(DbHelper.DB_NAME,0,null);StringBuilder schema=new StringBuilder("CREATE TABLE contacts(_id INTEGER PRIMARY KEY AUTOINCREMENT,favorite INTEGER NOT NULL DEFAULT 0");for(String col:DbHelper.TEXT_COLUMNS)if(!col.equals("met_at")&&!col.equals("met_place")&&!col.equals("meeting_notes"))schema.append(", ").append(col).append(" TEXT NOT NULL DEFAULT ''");old.execSQL(schema+")");old.execSQL("INSERT INTO contacts(name,company1,mobile1,favorite) VALUES('김민수','가나다','010-1234-5678',1)");old.setVersion(2);old.close();
        DbHelper db=new DbHelper(ctx);check(db.count()==1,"migration count");check(db.get(1).get("mobile1").equals("010-1234-5678"),"migration preserves phone");check(db.get(1).get("met_at").equals(""),"new column default");
        Contact second=card("박영수","바다","010-9999-0000");second.put("met_at","2026-10-07");second.put("met_place","대구 & 서울");second.put("meeting_notes","첫 만남\n후속 전화 예약");second.put("note1","=1+2\n한글, 따옴표 \"확인\"");second.id=db.insert(second);check(db.search("",false,"",1).get(0).id==second.id,"newest input first without favorite priority");check(db.search("ㄱㅁㅅ 123456",false,"",1).size()==1,"initials and normalized phone search");db.setGroup(second.id,"고객");check(db.search("",false,"고객",1).size()==1,"group filter");check(db.search("",true,"",1).size()==1,"favorite filter");second=db.get(second.id);second.put("updated_at","2026-10-08 10:00:00");db.update(second);check(db.search("",false,"",1).get(0).id==second.id,"editing preserves input order");
        File xlsx=new File(ctx.getCacheDir(),"checks.xlsx");DataExchange.writeXlsx(xlsx,db.all());List<Map<String,String>> rows=XlsxReader.readFirstSheet(xlsx);check(rows.size()==2,"xlsx row count");check(rows.get(1).get("메모1").equals(second.get("note1")),"xlsx formula stays text and preserves quotes/newlines");check(rows.get(1).get("휴대폰1").equals("010-9999-0000"),"xlsx phone leading zero");check(rows.get(1).get("만난 장소").equals("대구 & 서울"),"xlsx XML escaping");
        File csv=new File(ctx.getCacheDir(),"checks.csv");DataExchange.writeCsv(csv,db.all());String csvText=read(csv);check(csvText.startsWith("\ufeff"),"csv BOM");check(csvText.contains("'=1+2"),"csv formula protection");check(csvText.contains("\"\"확인\"\""),"csv quote escaping");
        File vcf=new File(ctx.getCacheDir(),"checks.vcf");Contact longName=card(longKorean(),"회사","010-1111-2222");DataExchange.writeVcard(vcf,Arrays.asList(second,longName));String v=read(vcf);for(String line:v.split("\r\n"))check(line.getBytes("UTF-8").length<=75,"vcard utf8 folding");check(v.contains("TEL;TYPE=CELL:010-9999-0000"),"vcard phone");check(v.contains("\\n"),"vcard note escaping");
        Bitmap image=Bitmap.createBitmap(160,80,Bitmap.Config.ARGB_8888);image.eraseColor(Color.BLUE);String photo=ImageUtil.saveBitmap(ctx,image,"check");injectOrientation(photo);Bitmap oriented=ImageUtil.oriented(photo,900);check(oriented.getWidth()==80&&oriented.getHeight()==160,"EXIF portrait rotation");second.put("image_front",photo);db.update(second);
        // Backups round-trip every new field and copy images, including older empty fields.
        File backup=BackupManager.createBackup(ctx,db);db.close();ctx.deleteDatabase(DbHelper.DB_NAME);db=new DbHelper(ctx);BackupManager.RestoreResult rr=BackupManager.restoreBackup(ctx,backup,db);check(rr.added==2&&db.count()==2,"backup restore count");Contact restored=db.search("박영수",false,"",1).get(0);check(restored.get("meeting_notes").equals("첫 만남\n후속 전화 예약"),"backup meeting notes");check(new File(restored.get("image_front")).isFile(),"backup photo");BackupManager.restoreBackup(ctx,backup,db);check(db.count()==2,"restore idempotence");
        Contact duplicate=card("박영수","바다","010-9999-0000");duplicate.put("email1","extra@example.com");duplicate.put("title1","추가 직위");duplicate.put("image_back",restored.get("image_front"));long duplicateId=db.insert(duplicate);restored.put("title1","기존 직위");db.update(restored);db.mergeAndDelete(restored.id,duplicateId);Contact merged=db.get(restored.id);check(db.get(duplicateId)==null&&merged.get("email1").equals("extra@example.com"),"duplicate merge fills blanks");check(merged.get("image_back").isEmpty(),"merge avoids duplicate photo paths");check(merged.get("title1").equals("기존 직위")&&merged.get("note3").contains("추가 직위"),"conflict retained in notes");db.renameGroup("고객","거래처");check(db.search("",false,"거래처",1).size()==1,"group rename");
        sharingChecks(ctx,db,merged);
        Map<String,String> parsed=OcrParser.parse("삼성전자\n김민수\n대표\n010-1234-5678\nFax 053-123-4567\nlsi@example.com");check("김민수".equals(parsed.get("name")),"OCR name excludes short company");check("053-123-4567".equals(parsed.get("fax1")),"OCR fax separate from phone");check(!parsed.containsKey("website"),"OCR email is not a website");
        Bitmap ocrImage=Bitmap.createBitmap(1800,900,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(ocrImage);canvas.drawColor(Color.WHITE);Paint textPaint=new Paint(Paint.ANTI_ALIAS_FLAG);textPaint.setColor(Color.BLACK);textPaint.setTextSize(88);textPaint.setTypeface(Typeface.createFromAsset(ctx.getAssets(),"NotoSansKR.ttf"));canvas.drawText("김민수",70,160,textPaint);canvas.drawText("주식회사 LSI",70,310,textPaint);canvas.drawText("010-1234-5678",70,460,textPaint);canvas.drawText("lsi@example.com",70,610,textPaint);String ocrPath=ImageUtil.saveBitmap(ctx,ocrImage,"ocr_fixture");java.util.concurrent.CountDownLatch latch=new java.util.concurrent.CountDownLatch(1);final String[] recognized={null};final Exception[] failure={null};OcrHelper.recognize(ctx,ocrPath,new OcrHelper.Callback(){public void onSuccess(String text){recognized[0]=text;latch.countDown();}public void onError(Exception e){failure[0]=e;latch.countDown();}});check(latch.await(90,java.util.concurrent.TimeUnit.SECONDS),"OCR timeout");check(failure[0]==null,"OCR runtime failure: "+failure[0]);check(recognized[0]!=null&&recognized[0].contains("010"),"bundled Korean OCR reads fixture");
        check(PhoneDisplay.format("01012345678").equals("010-1234-5678"),"mobile display");check(PhoneDisplay.format("025551234").equals("02-555-1234"),"Seoul display");check(PhoneDisplay.format("0538035160").equals("053-803-5160"),"regional display");check(PhoneDisplay.format("+82 10 1234 5678").equals("+82 10 1234 5678"),"international preserved");
        merged=db.get(merged.id);merged.put("image_front",ocrPath);merged.put("mobile1","01099990000");merged.put("source","CamCard");db.update(merged);
        for(int i=0;i<10;i++){Contact extra=card("테스트 "+i,i%2==0?"아주 긴 회사명과 부서 이름 표시를 확인하는 주식회사 · 영업관리부":"LSI","01012345678");extra.put("title1","담당자");extra.put("image_front",ocrPath);db.insert(extra);}
        ctx.getSharedPreferences("MainActivity",Context.MODE_PRIVATE).edit().putInt("sortMode",0).remove("recentDefault21").commit();
        final long editId=merged.id;
        Activity main=startActivitySync(new Intent(ctx,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();screenshot("main");check(find(main.getWindow().getDecorView(),"명함 스캔")!=null,"main scan entry");check(find(main.getWindow().getDecorView(),"최근 저장순 ▾")!=null,"upgrade switches default to recent order");ListView rowsView=findList(main.getWindow().getDecorView());check(rowsView!=null&&((Contact)rowsView.getAdapter().getItem(0)).id==db.search("",false,"",1).get(0).id,"main newest row");check(rowsView.getChildCount()>=4,"compact layout shows at least four rows");ActivityMonitor detailMonitor=addMonitor(DetailActivity.class.getName(),null,false);View firstRow=rowsView.getChildAt(0);int[] screenLocation=new int[2];runOnMainSync(()->firstRow.getLocationOnScreen(screenLocation));long tapTime=android.os.SystemClock.uptimeMillis();sendPointerSync(android.view.MotionEvent.obtain(tapTime,tapTime,android.view.MotionEvent.ACTION_DOWN,screenLocation[0]+35,screenLocation[1]+firstRow.getHeight()/2f,0));sendPointerSync(android.view.MotionEvent.obtain(tapTime,tapTime+40,android.view.MotionEvent.ACTION_UP,screenLocation[0]+35,screenLocation[1]+firstRow.getHeight()/2f,0));Activity tapped=detailMonitor.waitForActivityWithTimeout(2000);removeMonitor(detailMonitor);check(tapped!=null,"row remains tappable beside quick menu");runOnMainSync(tapped::finish);waitForIdleSync();View addMenu=findDescription(main.getWindow().getDecorView(),"명함 추가 메뉴");check(addMenu!=null,"top add menu");runOnMainSync(addMenu::performClick);waitForIdleSync();screenshot("add-menu");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);waitForIdleSync();View cardMenu=findDescription(main.getWindow().getDecorView(),"테스트 9 빠른 메뉴");check(cardMenu!=null,"row quick menu");runOnMainSync(cardMenu::performClick);waitForIdleSync();screenshot("card-menu");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);waitForIdleSync();View manage=find(main.getWindow().getDecorView(),"관리");runOnMainSync(manage::performClick);waitForIdleSync();screenshot("manage-panel");activeClick("현재 목록 내보내기");waitForIdleSync();screenshot("export-formats");activeClick("Excel (.xlsx) · 연락처 정보");waitForIdleSync();screenshot("export-methods");activeClick("이메일 · Quick Share · 블루투스 공유");android.os.SystemClock.sleep(1200);waitForIdleSync();screenshot("share-sheet");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);waitForIdleSync();EditText query=findEdit(main.getWindow().getDecorView());runOnMainSync(()->query.setText("존재하지않는검색어"));waitForIdleSync();check(find(main.getWindow().getDecorView(),"검색 결과가 없습니다.\n검색어 또는 즐겨찾기·그룹 조건을 확인하세요.")!=null,"empty search has correct guidance");runOnMainSync(main::finish);waitForIdleSync();
        Activity detail=startActivitySync(new Intent(ctx,DetailActivity.class).putExtra("id",editId).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();screenshot("detail");View cardPhoto=findDescription(detail.getWindow().getDecorView(),"명함 앞면 사진 확대");check(cardPhoto!=null,"detail photo opens viewer");runOnMainSync(cardPhoto::performClick);waitForIdleSync();screenshot("photo-viewer");sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);waitForIdleSync();View more=find(detail.getWindow().getDecorView(),"추가 정보 ▾");check(more!=null,"detail expandable metadata");runOnMainSync(more::performClick);waitForIdleSync();check(find(detail.getWindow().getDecorView(),"가져온 곳\nCamCard")!=null,"source accessible");check(db.get(editId).get("mobile1").equals("01099990000"),"detail leaves stored phone untouched");runOnMainSync(detail::finish);waitForIdleSync();
        ctx.getSharedPreferences("display",Context.MODE_PRIVATE).edit().putInt("size",2).commit();Activity large=startActivitySync(new Intent(ctx,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();screenshot("main-large");check(find(large.getWindow().getDecorView(),"명함 스캔")!=null,"large text scan entry");runOnMainSync(large::finish);waitForIdleSync();ctx.getSharedPreferences("display",Context.MODE_PRIVATE).edit().putInt("size",0).commit();
        Activity edit=startActivitySync(new Intent(ctx,EditActivity.class).putExtra("id",editId).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();screenshot("edit");check(find(edit.getWindow().getDecorView(),"만남 기록")!=null,"meeting editor UI");runOnMainSync(edit::finish);waitForIdleSync();
        Activity crop=startActivitySync(new Intent(ctx,PhotoEditActivity.class).putExtra("path",photo).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();screenshot("photo");View rotate=find(crop.getWindow().getDecorView(),"90° 회전");View use=find(crop.getWindow().getDecorView(),"이 사진 사용");check(rotate!=null&&use!=null,"photo editor controls");runOnMainSync(()->{rotate.performClick();use.performClick();});waitForIdleSync();check(crop.isFinishing(),"photo edit commits");db.close();
    }
    private void sharingChecks(Context ctx,DbHelper db,Contact sample)throws Exception{
        String[] extensions={".xlsx",".csv",".vcf",".zip"},types={"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","text/vcard","application/zip"};
        File previous=null;byte[] previousBytes=null;
        for(int i=0;i<extensions.length;i++){
            File file=i==3?BackupManager.createBackup(ctx,Collections.singletonList(sample)):ExportShare.newFile(ctx,"내보내기_검사",extensions[i]);
            if(i==0)DataExchange.writeXlsx(file,Collections.singletonList(sample));if(i==1)DataExchange.writeCsv(file,Collections.singletonList(sample));if(i==2)DataExchange.writeVcard(file,Collections.singletonList(sample));
            Intent intent=ExportShare.sendIntent(ctx,file);android.net.Uri uri=intent.getParcelableExtra(Intent.EXTRA_STREAM);check(Intent.ACTION_SEND.equals(intent.getAction())&&types[i].equals(intent.getType()),"share type "+extensions[i]);check("content".equals(uri.getScheme()),"content attachment URI");check(intent.getClipData()!=null&&intent.getClipData().getItemAt(0).getUri().equals(uri),"ClipData URI grant");check((intent.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION)!=0&&(intent.getFlags()&Intent.FLAG_GRANT_WRITE_URI_PERMISSION)==0,"read-only grant");
            try(android.database.Cursor cursor=ctx.getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.SIZE,android.provider.OpenableColumns.DISPLAY_NAME},null,null,null)){check(cursor!=null&&cursor.moveToFirst()&&cursor.getLong(0)==file.length()&&cursor.getString(1).equals(file.getName()),"receiver filename and size projection");}
            byte[] expected=bytes(new FileInputStream(file));check(Arrays.equals(expected,bytes(ctx.getContentResolver().openInputStream(uri))),"attachment is readable");boolean denied=false;try(OutputStream out=ctx.getContentResolver().openOutputStream(uri,"w")){}catch(Exception e){denied=true;}check(denied&&file.length()==expected.length,"exports reject writes");
            java.util.concurrent.CountDownLatch received=new java.util.concurrent.CountDownLatch(1);final Intent[] report={null};BroadcastReceiver receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent message){report[0]=message;received.countDown();}};IntentFilter filter=new IntentFilter("com.lsi.businesscard.TEST_ATTACHMENT_READ");if(android.os.Build.VERSION.SDK_INT>=33)ctx.registerReceiver(receiver,filter,Context.RECEIVER_EXPORTED);else ctx.registerReceiver(receiver,filter);try{ctx.startActivity(new Intent(intent).setComponent(new ComponentName("com.lsi.businesscard.test","com.lsi.businesscard.AttachmentReceiver")).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));check(received.await(15,java.util.concurrent.TimeUnit.SECONDS),"external receiver timeout");check(report[0].getStringExtra("error")==null,"receiver error: "+report[0].getStringExtra("error"));check(report[0].getIntExtra("uid",-1)!=android.os.Process.myUid(),"receiver has separate UID");check(Arrays.equals(java.security.MessageDigest.getInstance("SHA-256").digest(expected),report[0].getByteArrayExtra("digest")),"external receiver reads attachment "+extensions[i]);check(types[i].equals(report[0].getStringExtra("mime"))&&file.getName().equals(report[0].getStringExtra("name")),"external receiver MIME and filename");}finally{ctx.unregisterReceiver(receiver);}
            if(i==3){try(java.util.zip.ZipFile zip=new java.util.zip.ZipFile(file)){org.json.JSONObject json=new org.json.JSONObject(new String(bytes(zip.getInputStream(zip.getEntry("contacts.json"))),"UTF-8"));check(json.getJSONArray("contacts").length()==1,"selected ZIP contains only selected card");String entry=json.getJSONArray("contacts").getJSONObject(0).getString("image_front");check(zip.getEntry(entry)!=null,"selected ZIP includes card photo");}}
            if(previous!=null)check(Arrays.equals(previousBytes,bytes(new FileInputStream(previous))),"new export preserves earlier attachment");previous=file;previousBytes=expected;
        }
        boolean denied=false;try{CardFileProvider.uriFor(ctx,ctx.getDatabasePath(DbHelper.DB_NAME));}catch(SecurityException e){denied=true;}check(denied,"private DB is not exposed");
        android.net.Uri bad=new android.net.Uri.Builder().scheme("content").authority(CardFileProvider.AUTHORITY).appendPath("exports").appendPath("../contacts.db").build();denied=false;try(InputStream input=ctx.getContentResolver().openInputStream(bad)){}catch(Exception e){denied=true;}check(denied,"URI traversal is rejected");
        File camera=CardFileProvider.newCameraFile(ctx,"provider_check");try(OutputStream out=ctx.getContentResolver().openOutputStream(CardFileProvider.uriFor(ctx,camera),"w")){out.write(new byte[]{1,2,3});}check(camera.length()==3,"camera remains writable");camera.delete();
    }
    private byte[] bytes(InputStream input)throws Exception{if(input==null)throw new IOException("null stream");try(InputStream in=input;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);return out.toByteArray();}}
    private void activeClick(String text)throws Exception{android.os.SystemClock.sleep(250);android.view.accessibility.AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();check(root!=null,"dialog accessibility root");for(android.view.accessibility.AccessibilityNodeInfo node:root.findAccessibilityNodeInfosByText(text)){if(node.getText()!=null&&text.equals(node.getText().toString())){android.view.accessibility.AccessibilityNodeInfo target=node;for(int depth=0;depth<4&&target!=null;depth++,target=target.getParent())if(target.isClickable()){check(target.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK),"click "+text);return;}}}throw new AssertionError("missing menu action "+text);}
    private void injectOrientation(String path)throws Exception{byte[] data;try(InputStream in=new FileInputStream(path);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);data=out.toByteArray();}String hex="FFE1002245786966000049492A0008000000010012010300010000000600000000000000";try(OutputStream out=new FileOutputStream(path)){out.write(data,0,2);for(int i=0;i<hex.length();i+=2)out.write(Integer.parseInt(hex.substring(i,i+2),16));out.write(data,2,data.length-2);}}
    private void screenshot(String name)throws Exception{android.os.SystemClock.sleep(350);waitForIdleSync();Bitmap b=getUiAutomation().takeScreenshot();if(b!=null)try(OutputStream out=new FileOutputStream(new File(getTargetContext().getExternalFilesDir(null),name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}}
    private View findDescription(View view,String text){if(text.contentEquals(view.getContentDescription()==null?"":view.getContentDescription()))return view;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){View v=findDescription(g.getChildAt(i),text);if(v!=null)return v;}}return null;}
    private EditText findEdit(View view){if(view instanceof EditText)return (EditText)view;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){EditText v=findEdit(g.getChildAt(i));if(v!=null)return v;}}return null;}
    private ListView findList(View view){if(view instanceof ListView)return (ListView)view;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){ListView v=findList(g.getChildAt(i));if(v!=null)return v;}}return null;}
    private String longKorean(){StringBuilder b=new StringBuilder();for(int i=0;i<10;i++)b.append("가나다라마바사아자차카타파하");return b.toString();}
    private View find(View view,String text){if(view instanceof TextView&&((TextView)view).getText().toString().equals(text))return view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){View found=find(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
    private String read(File f)throws Exception{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8");}}
}
